# Generated by Django 2.1.7 on 2019-07-22 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('achive', models.CharField(max_length=15)),
                ('discription', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('pass_out', models.CharField(max_length=15)),
                ('job', models.CharField(max_length=15)),
                ('discription', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='login_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='student_join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=15)),
                ('father_email', models.CharField(max_length=15)),
                ('father_contact', models.CharField(max_length=50)),
                ('mother_email', models.CharField(max_length=15)),
                ('mother_contact', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 7, 22, 19, 54, 5, 381967))),
            ],
        ),
        migrations.CreateModel(
            name='teacher_join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=15)),
                ('post', models.CharField(max_length=15)),
                ('experience', models.CharField(max_length=15)),
                ('last_school', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 7, 22, 19, 54, 5, 334095))),
            ],
        ),
    ]
