# Generated by Django 2.1.7 on 2019-07-22 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_join',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 20, 1, 4, 548084)),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 20, 1, 4, 521186)),
        ),
    ]
