# Generated by Django 2.1.7 on 2019-09-22 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190722_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='achive',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login_admin',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login_admin',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login_admin',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login_admin',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='management',
            name='designation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 20, 17, 38, 547173)),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='father_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='father_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='father_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='mother_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='mother_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_join',
            name='mother_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 20, 17, 38, 515931)),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='last_school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='post',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
