# Generated by Django 2.1.7 on 2019-10-05 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190922_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_join',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 27, 19, 559218)),
        ),
        migrations.AlterField(
            model_name='teacher_join',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 27, 19, 539397)),
        ),
    ]
