from django.urls import path
from . import views
from django.conf import settings

urlpatterns=[
    path('admin_index/',views.admin_index,name="admin_index"),
    path('upload_admin_index/',views.uplode_admin_index,name="upload_admin_index"),
    path('save_admin_index/',views.save_admin_index,name="save_admin_index"),
    path('join_request/',views.join_request,name="join_request"),
    path('logout/',views.logout,name="logout"),
    path('delete_alumni/',views.delete_alumni,name="delete_alumni"),
    path('delete_achivement/',views.delete_achivement,name="delete_achivement"),
    path('delete_event/',views.delete_event,name="delete_event"),
    path('delete_facility/',views.delete_facility,name="delete_facility"),
    path('delete_management/',views.delete_management,name="delete_management"),
    path('delete_student/',views.delete_student,name="delete_student"),
    path('delete_teacher/',views.delete_teacher,name="delete_teacher"),   
    path('bhayander_admin_index/',views.bhayander_admin_index,name="bhayander_admin_index"),
    path('bhayander_admin_kinder_garten/',views.bhayander_admin_kinder_garten,name="bhayander_admin_kinder_garten"),
    path('bhayander_admin_primary/',views.bhayander_admin_primary,name="bhayander_admin_primary"),
    path('bhayander_admin_secondary/',views.bhayander_admin_secondary,name="bhayander_admin_secondary"),
    path('bhayander_admin_college/',views.bhayander_admin_college,name="bhayander_admin_college"),
    path('upload_admin_bhayander/',views.uplode_admin_bhayander,name="upload_admin_bhayander"),
    path('save_admin_bhayander/',views.save_admin_bhayander,name="save_admin_bhayander"),
    path('delete_bhayander/',views.delete_bhayander,name="delete_bhayander"),
    path('nalasopara_admin_index/',views.nalasopara_admin_index,name="nalasopara_admin_index"),
    path('nalasopara_admin_kinder_garten/',views.nalasopara_admin_kinder_garten,name="nalasopara_admin_kinder_garten"),
    path('nalasopara_admin_primary/',views.nalasopara_admin_primary,name="nalasopara_admin_primary"),
    path('nalasopara_admin_secondary/',views.nalasopara_admin_secondary,name="nalasopara_admin_secondary"),
    path('delete_nalasopara/',views.delete_nalasopara,name="delete_nalasopara"),
    path('upload_admin_nalasopara/',views.uplode_admin_nalasopara,name="upload_admin_nalasopara"),
    path('save_admin_nalasopara/',views.save_admin_nalasopara,name="save_admin_nalasopara"),
    path('virar_admin_index/',views.virar_admin_index,name="virar_admin_index"),
    path('virar_admin_primary/',views.virar_admin_primary,name="virar_admin_primary"),
    path('virar_admin_secondary/',views.virar_admin_secondary,name="virar_admin_secondary"),
    path('delete_virar/',views.delete_virar,name="delete_virar"),
    path('upload_admin_virar/',views.uplode_admin_virar,name="upload_admin_virar"),
    path('save_admin_virar/',views.save_admin_virar,name="save_admin_virar"),
    path('',views.admin_url_redirect),
]