# Generated by Django 2.1.7 on 2019-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bhayander_achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('achive', models.CharField(max_length=15)),
                ('discription', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_juniorCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_juniorCollege_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_kinderGarten_english',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_kinderGarten_english_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_kinderGarten_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_kinderGarten_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_primary_english',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_primary_english_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_primary_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_primary_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_secondary_english',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_secondary_english_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_secondary_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='bhayander_secondary_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('achive', models.CharField(max_length=15)),
                ('discription', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_kinderGarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_kinderGarten_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_primary_english',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_primary_english_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_primary_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_primary_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_secondary_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='nalasopara_secondary_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('achive', models.CharField(max_length=15)),
                ('discription', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_primary_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_primary_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_secondary_hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='virar_secondary_hindi_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1500)),
            ],
        ),
    ]
