# Generated by Django 2.1.7 on 2019-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhayander_achivement',
            name='achive',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bhayander_achivement',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nalasopara_achivement',
            name='achive',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nalasopara_achivement',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='virar_achivement',
            name='achive',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='virar_achivement',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
